#' Plot the deduplication stats for MarkDuplicates
#'
#' @param fgb_stats The stats file generated by MarkDuplicates

plot_stats_MD <- function(md_stats) {
  # Read all lines of md_stats file. Then remove every line until the line that starts with "BIN"
  md_stats <- readLines(md_stats)
  md_stats <- md_stats[which(str_detect(md_stats, "^BIN")):length(md_stats)]
  
  # The first line is the header, use it
  md_stats <- read.table(text = md_stats, header = TRUE, sep = "\t")
  
  # Plot the stats
  ggplot(md_stats, aes(x = BIN, y = all_sets)) +
    geom_bar(stat = "identity") +
    labs(x = "MD", y = "Count") +
    theme_bw()
}