#' Plot the deduplication stats for fgbio
#' 
#' @param fgb_stats The stats file generated by fgbio

plot_stats_FGB <- function(fgb_stats) {
  fgb_stats <- read.table(fgb_stats, header = TRUE, sep = "\t")
  
  # Plot the stats
  ggplot(fgb_stats, aes(x = family_size, y = count)) +
    geom_bar(stat = "identity") +
    labs(x = "Family size", y = "Count") +
    theme_bw()
  
}