#' Plot the deduplication stats for UMItools
#'
#' @param fgb_stats The stats file generated by UMItools

plot_stats_UT <- function(ut_stats) {
  ut_stats <- read.table(ut_stats, header = TRUE, sep = "\t")
  
  # Plot the stats
  ggplot(ut_stats, aes(x = counts, y = instances_pre)) +
    geom_bar(stat = "identity") +
    labs(x = "Family size", y = "Count") +
    theme_bw()
  
}